AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'

Documentation:
  Enabled: false

MultilineOperationIndentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'spec/support/serializer_helpers.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'

Style/AlignParameters:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/AlignHash:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MutableConstant:
  Enabled: false
