admin_name: Admin User
admin_email: admin@minutehero.net
admin_password: minher0!

domain_name: minutehero.net
secret_key_base: 76d92e34d33ad897f8e9d3e5fe047768e0c73440aa02d2c232f5bc45f6e8c2fefaf1a2ec6f005ac051f5d5a2881bf5217a30ae7f989d0d2dcbb69b9a05a5d41f

mailjet_api_key: c6cd8caa8d65ae490a84ceaf438a7510
mailjet_secret_key: 2422bac1bf4651eb6dd0053363477e6b

linkedin_client_id:	77y16gklqckatk
linkedin_client_secret:	pgMDhaaXd9jOPdWE

facebook_app_id: 1328975933825169
facebook_secret: 9e8d2af6be96716e4c443c20e01d6cd4

recaptcha_site_key: 6LcGuRAUAAAAAN_g8Qyypn1onQ3bvjeXa3jIncHl
recaptcha_secret_key: 6LcGuRAUAAAAADJunJ11TruZMnMc0pEg_dl-rxzC

staging:
 domain_name: staging.minutehero.net

production:
 domain_name: my.minutehero.net
