default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  database: minutehero
  username: postgres
  password: postgres
  template: template0

development:
  <<: *default

test:
  <<: *default
  database: minutehero_test

staging:
  <<: *default

production:
  <<: *default
  host:     rds-minutehero-production-1.cdxuwzcuekg6.eu-west-1.rds.amazonaws.com
  port:     5432
  username: rdsroot
  password: m1GVkbyaf78tdmmrDJtN
