default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  database: minutehero
  username: postgres
  password: postgres
  template: template0

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
