# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d92e34d33ad897f8e9d3e5fe047768e0c73440aa02d2c232f5bc45f6e8c2fefaf1a2ec6f005ac051f5d5a2881bf5217a30ae7f989d0d2dcbb69b9a05a5d41f

test:
  secret_key_base: 9d83a9d3ec0b43f21c758a58c65e259fa89f2c7ed3980e1bb804363db496b71a30d08d1770f2e87d4ba73e5b883381163ca6a7fc74fa466a41ba185f8d2e2e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
