module ApplicationHelper
  # rubocop:disable MethodLength, AbcSize
  def sort_column_by(column, title = '')
    # initialize values
    sort = :desc
    # The following instruction was commented to remove the related warning
    # generated by Rubocop about useless assignment
    # To be reviewed later in coming releases
    # icon_class = 'sort'
    column_title = if title.blank?
                     ActiveSupport::Inflector.titleize(column)
                   else
                     title
                   end

    # sort order
    if params[:column] == column.to_s
      sort = params[:sort] == 'asc' ? :desc : :asc
      # The following instruction was commented to remove the related warning
      # generated by Rubocop about useless assignment
      # To be reviewed later in coming releases
      # icon_class = "sort-#{sort}"
    end

    # header with link
    link_to Rails.application.routes.url_helpers.send(
      :"#{request.path[1..-1]}_path",
        request.query_parameters.merge(column: column, sort: sort)
    ),
    class: 'sort-link', title: sort do
      # This instruction triggers an error as icon seems to be unknown
      # To be reviewed later in coming releases
      # icon icon_class, column_title
      column_title
    end
  end

  def yesno(x)
    x ? 'Yes' : 'No'
  end

  def flash_class(level)
    case level
    when 'notice' then 'alert alert-dismissable alert-info'
    when 'success' then 'alert alert-dismissable alert-success'
    when 'error' then 'alert alert-dismissable alert-danger'
    when 'recaptcha_error' then 'alert alert-dismissable alert-danger'
    when 'alert' then 'alert alert-dismissable alert-warning'
    end
  end
end
